// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateOneUser(ctx context.Context, arg CreateOneUserParams) error
	CreateVerificationUser(ctx context.Context, arg CreateVerificationUserParams) error
	DeleteOneUser(ctx context.Context, id string) error
	DeleteVerificationUser(ctx context.Context, email string) error
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetUserById(ctx context.Context, id string) (User, error)
	GetVerificationUser(ctx context.Context, email string) (Verification, error)
	UpdateOneUser(ctx context.Context, arg UpdateOneUserParams) error
	UserAlreadyExists(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
