// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
	"time"
)

const createOneUser = `-- name: CreateOneUser :exec
INSERT INTO users (id, first_name, last_name, email, password, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOneUserParams struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateOneUser(ctx context.Context, arg CreateOneUserParams) error {
	_, err := q.db.ExecContext(ctx, createOneUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateOneUser = `-- name: UpdateOneUser :exec
UPDATE users SET first_name=$2, last_name=$3
WHERE id=$1
`

type UpdateOneUserParams struct {
	ID        string
	FirstName string
	LastName  string
}

func (q *Queries) UpdateOneUser(ctx context.Context, arg UpdateOneUserParams) error {
	_, err := q.db.ExecContext(ctx, updateOneUser, arg.ID, arg.FirstName, arg.LastName)
	return err
}
